services:
  neurocreatives:
    build: .
    container_name: neurocreatives
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - CHANNELS_TO_PARSE=${CHANNELS_TO_PARSE}
    volumes:
      - ./downloads:/app/downloads
      - ./parser_session.session:/app/parser_session.session
    dns:
      - 8.8.8.8
      - 8.8.4.4
    network_mode: host

networks:
  neurocreatives-network:
    driver: bridge
